frr defaults traditional
hostname {name}
log file /tmp/frr_{name}/frr.log
!
interface lo
 ip address {loopback_ip}/32
 ip ospf area 0
!
interface {name}-eth0
 ip ospf network point-to-point
 ip ospf area 0
!
router ospf
 ospf router-id {loopback_ip}
 network 10.0.0.0/8 area 0
 network 172.16.0.0/16 area 0
 network {loopback_ip}/32 area 0
 redistribute connected
 redistribute static
 redistribute kernel
!
mpls ldp
 router-id {loopback_ip}
 address-family ipv4
  discovery transport-address {loopback_ip}
  interface lo
  interface {name}-eth0
 !
!
line vty
!
